In [1]:
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [3]:
## Load Data 
df = pd.read_csv("Churn_Modelling.csv")

In [4]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [43]:
df.head(2)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0


In [44]:
# Preprocessing Data

X = df.iloc[:,3:-1]
y = df.iloc[:,-1]

In [45]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52


In [46]:
df['Gender'].value_counts()
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [47]:
encoder  = LabelEncoder()
X['Gender']=encoder.fit_transform(X['Gender'])    

In [48]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,0,42,2,0.00,1,1,1,101348.88
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58
2,502,France,0,42,8,159660.80,3,1,0,113931.57
3,699,France,0,39,1,0.00,2,0,0,93826.63
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64
9996,516,France,1,35,10,57369.61,1,1,1,101699.77
9997,709,France,0,36,7,0.00,1,0,1,42085.58
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52


In [49]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [50]:
## OHE on Geography

from sklearn.preprocessing import OneHotEncoder
ohe_encoder = OneHotEncoder(sparse_output=False)
geo_encoded = ohe_encoder.fit_transform(df[['Geography']])

In [51]:
geo_encoded

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [52]:
ohe_encoder.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [53]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns = ohe_encoder.get_feature_names_out())

In [54]:
X = pd.concat([X,geo_encoded_df],axis = 1)

In [55]:
X

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,France,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,France,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0


In [56]:
X.drop(['Geography'],axis=1,inplace=True)

In [57]:
X

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,0.0,1.0,0.0


In [58]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [ ]:
## Save encder and Scalers
with open('label_encoder_geography.pkl','wb') as file:
    pickle.dump(ohe_encoder,file)

with open('label_encoder_gender.pkl','wb') as file:
    pickle.dump(encoder,file)

In [60]:
X_train,X_test,Y_train,Y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [61]:
X_train

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
9254,686,1,32,6,0.00,2,1,1,179093.26,1.0,0.0,0.0
1561,632,1,42,4,119624.60,2,1,1,195978.86,0.0,1.0,0.0
1670,559,1,24,3,114739.92,1,1,0,85891.02,0.0,0.0,1.0
6087,561,0,27,9,135637.00,1,1,0,153080.40,1.0,0.0,0.0
6669,517,1,56,9,142147.32,1,0,0,39488.04,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
5734,768,1,54,8,69712.74,1,1,1,69381.05,1.0,0.0,0.0
5191,682,0,58,1,0.00,1,1,1,706.50,1.0,0.0,0.0
5390,735,0,38,1,0.00,3,0,0,92220.12,1.0,0.0,0.0
860,667,1,43,8,190227.46,1,1,0,97508.04,1.0,0.0,0.0


In [62]:
# Scaling Features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [63]:
X_train.shape

(8000, 12)

In [64]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [65]:
X_test_tensor.shape

torch.Size([8000, 12])

In [66]:
import torch
import torch.nn as nn

In [67]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)

In [68]:
Y_train_tensor = torch.tensor(Y_train.values)

In [69]:
Y_test_tensor = torch.tensor(Y_test.values)

In [70]:
class AnnModel(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features.shape[1],8),
            nn.ReLU(),
            nn.Linear(8,4),
            nn.ReLU(),
            nn.Linear(4,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        output = self.network(features)
        return output

In [71]:
X_test_tensor.shape

torch.Size([2000, 12])

In [102]:
model = AnnModel(X_train_tensor)
Learning_rate = 0.1
epochs = 5000
Loss_function = nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(),Learning_rate)

In [ ]:
Y_train_tensor = Y_train_tensor.view(-1,1).to(torch.float32)
# y_pred = y_pred.view(-1,1).to(torch.float32)
from torch.utils.tensorboard import SummaryWriter
# writer = SummaryWriter('runs/ann_experiment_1')

for epoch in range(epochs):
    y_pred = model(X_train_tensor.to(torch.float32))
    loss = Loss_function(y_pred,Y_train_tensor.to(torch.float32))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    print(f"Epoch: {epoch+1},Loss: {loss.item()}")
    # writer.add_scalar('Loss/train', loss.item(), epoch)
# writer.close()

Epoch: 1,Loss: 0.3290444612503052
Epoch: 2,Loss: 0.3290429413318634
Epoch: 3,Loss: 0.3290414810180664
Epoch: 4,Loss: 0.329039990901947
Epoch: 5,Loss: 0.32903850078582764
Epoch: 6,Loss: 0.32903704047203064
Epoch: 7,Loss: 0.3290356397628784
Epoch: 8,Loss: 0.32903414964675903
Epoch: 9,Loss: 0.3290327191352844
Epoch: 10,Loss: 0.3290312886238098
Epoch: 11,Loss: 0.32902979850769043
Epoch: 12,Loss: 0.3290281295776367
Epoch: 13,Loss: 0.3290264904499054
Epoch: 14,Loss: 0.3290247917175293
Epoch: 15,Loss: 0.3290230333805084
Epoch: 16,Loss: 0.32902130484580994
Epoch: 17,Loss: 0.32901957631111145
Epoch: 18,Loss: 0.3290178179740906
Epoch: 19,Loss: 0.3290161192417145
Epoch: 20,Loss: 0.32901421189308167
Epoch: 21,Loss: 0.329012393951416
Epoch: 22,Loss: 0.3290105164051056
Epoch: 23,Loss: 0.3290087580680847
Epoch: 24,Loss: 0.32900699973106384
Epoch: 25,Loss: 0.32900524139404297
Epoch: 26,Loss: 0.3290034830570221
Epoch: 27,Loss: 0.32900169491767883
Epoch: 28,Loss: 0.32899993658065796
Epoch: 29,Loss: 0.32

In [116]:
print(f"Predictions count: {predictions.shape[0]}")
print(f"Labels count: {Y_test_tensor.shape[0]}")
print(Y_train_tensor.shape)

Predictions count: 2000
Labels count: 2000
torch.Size([8000, 1])


The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


Reusing TensorBoard on port 6006 (pid 15985), started 0:00:09 ago. (Use '!kill 15985' to kill it.)

In [105]:
model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor.to(torch.float32)) 
    
    predictions = (test_outputs >= 0.5).float()
    
    Y_test_actual = Y_test_tensor.view(-1, 1).to(torch.float32)
    
    correct = (predictions == Y_test_actual).sum().item()
    accuracy = (correct / Y_test_actual.size(0)) * 100

print(f"Accuracy: {accuracy:.2f}%")

Accuracy: 86.15%


In [107]:
predictions.shape

torch.Size([2000, 1])

In [108]:
from sklearn.metrics import confusion_matrix


In [109]:
confusion_matrix = (Y_test_tensor,predictions)

In [110]:
confusion_matrix

(tensor([0, 0, 0,  ..., 1, 1, 1]),
 tensor([[0.],
         [0.],
         [0.],
         ...,
         [1.],
         [0.],
         [0.]]))

In [111]:
torch.save(model.state_dict(),'ann_model_weights.pth')

In [112]:
torch.save(model,'Ann-model.pth')